version: 0.2

phases:
  install:
    commands:
      - "npm install"
      - "npm install --global serverless"
      - "npm test"
  build:
    commands:
      - "serverless deploy"
artifacts:
  files:
    - "**/*"
