service: mission24

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-northeast-2

plugins:
  - serverless-offline

functions:
  app:
    handler: /src/serverless.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
